name: AYDO Client Test Deploy

on:
  push:
    branches: [ "AYDO-test" ]
  pull_request:
    branches: [ "AYDO-test" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins
      run: |
        curl -L --user ${{ secrets.JENKINS_AUTH_GCP }} "https://jk.aydo.ai/job/aydo-server/build?token=${{ secrets.JENKINS_API_TOKEN }}"
